name: JIRENGU_CI

on: pull_request_target
jobs:
  homework-judgement:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
              ğŸ‰ æ„Ÿè°¢æ‚¨æäº¤Pull Requestï¼è¯·ç¨ç­‰ç‰‡åˆ»ï¼Œæˆ‘ä»¬å·²ç»å°†å…¶æäº¤åˆ°CIè¿›è¡Œæ£€æŸ¥ï¼Œä¸€æ—¦æœ‰ç»“æœä¼šç«‹å³é€šçŸ¥æ‚¨ï¼
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Comment PR if tests pass
        if: ${{ success() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'All tests passed! ğŸ‰ Congratulation!ğŸ‰ğŸ‰ğŸ‰ We will revert your commit '
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR if tests fail
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Some tests failed. ğŸ˜ Please check the [ci logs](${{ github.event.pull_request._links.html.href }}/checks) for more details.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
      - name: Revert merged commit
        if: ${{ always() }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            if (pull.merged) {
              await github.rest.repos.createCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                message: `Revert "auto merge: ${pull.title}"`,
                tree: pull.base.sha,
                parents: [pull.merge_commit_sha],
              });
              console.log("Reverted the merged commit");
            } else {
              console.log("No need to revert, the PR was not merged");
            }
